spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://192.168.0.200/processos
    username: synccadastro
    password: 9BWAB1SW6S5UD7RTGN8IFA
  data:
    mongodb:
      username: prolink
      password: VFrs8RYp8CceZCeNGO474247bqafLdhK
      host: ec2-107-22-145-62.compute-1.amazonaws.com
      port: 27017
      database: prolink
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  config: src/main/resources/logback-dev.xml
planilha:
  origem: C:/TEMP/planilha.xls
  destino: C:/TEMP/syncFiles
  senha: 1234
  agendamento: 0 0 0,13,18 ? * MON-FRI
cliente:
  agendamento: 0 0 0 ? * SUN