spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost/processos
    username: admin
    password: admin
  data:
    mongodb:
      uri: ${MONGO_TEST_URI}
      #database: ${MONGO_DB:prolink}
      #username: ${MONGO_USER:prolink}
      #password: ${MONGO_PASSWORD:prolink}
      #host: ${MONGO_HOST:127.0.0.1}
      #port: 27017
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  config: classpath:logback-dev.xml
planilha:
  origem: C:/TEMP/planilha.xls
  destino: C:/TEMP/syncFiles
  senha: 1234
  agendamento: 0 0 0,13,18 ? * MON-FRI
cliente:
  agendamento: 0 0 0 ? * SUN